. ../scolors.sh

for c in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE REDBG GREENBG YELLOWBG BLUEBG MAGENTABG CYANBG BOLD UNDERLINE; do
  eval COLOR=\$${c}
  printf "${COLOR}ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890${NORMAL} \n"
done
